language: node_js
os: osx
osx_image: xcode9.2
node_js:
  - "8.1.4"
before_install:
  - npm install
  - npm rebuild wd
script:
  - npm test
  - npm run test:eslint
  - npm run test:sauce
#  - npm run build:cordova
notifications:
  email: true
sudo: false

addons:
  sauce_connect: true
